name: Update Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "42 23 * * *"

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set time zone
      run: |
        sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
        echo "Asia/Seoul" | sudo tee /etc/timezone
        date

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto update blog" || echo "No changes to commit"
        # 변경된 파일이 없으면 오류를 막기 위해 echo 실행

    - name: Push changes
      run: |
        # ❗ 수정됨 : 기존 URL push 삭제하고 origin 사용
        git push origin main
        # 기존의 잘못된 push URL을 제거함
